/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/articles": {
    /** @description article entityを全て取得 */
    get: {
      parameters: {
        query?: {
          /** @description asc or desc */
          order?: "asc" | "desc";
          /** @description ソートするカラム */
          order_by?: "id" | "created_at" | "updated_at";
        };
      };
      responses: {
        /** @description get article */
        200: {
          content: {
            "application/json": components["schemas"]["articleEntities"];
          };
        };
        /** @description articleが存在しない */
        404: {
          content: never;
        };
      };
    };
    /** @description articleの追加 */
    post: {
      requestBody: components["requestBodies"]["articleEntity"];
      responses: {
        /** @description post article */
        200: {
          content: {
            "application/json": components["schemas"]["articleEntity"];
          };
        };
      };
    };
  };
  "/v1/article/{article_id}": {
    /** @description article(単体)の取得 */
    get: {
      parameters: {
        path: {
          /** @description article id */
          article_id: number;
        };
      };
      responses: {
        /** @description get article */
        200: {
          content: {
            "application/json": components["schemas"]["articleEntity"];
          };
        };
      };
    };
    /** @description articleの更新 */
    put: {
      parameters: {
        path: {
          /** @description article id */
          article_id: number;
        };
      };
      requestBody: components["requestBodies"]["articleEntity"];
      responses: {
        /** @description put article */
        200: {
          content: {
            "application/json": components["schemas"]["articleEntity"];
          };
        };
      };
    };
    /** @description articleの削除 */
    delete: {
      parameters: {
        path: {
          /** @description article id */
          article_id: number;
        };
      };
      responses: {
        /** @description delete article */
        200: {
          content: {
            "application/json": components["schemas"]["articleEntity"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description 記事 */
    articleEntity: {
      /**
       * Format: int32
       * @description 記事を一意に判定するid
       */
      id?: number;
      /** @description 記事名 */
      name?: string;
      /** @description 記事内容 */
      body?: string;
      /**
       * Format: date-time
       * @description 記事の作成日時
       */
      created_at?: string;
      /**
       * Format: date-time
       * @description 記事の更新日時
       */
      updated_at?: string;
    };
    /** @description 記事の配列 */
    articleEntities: components["schemas"]["articleEntity"][];
  };
  responses: never;
  parameters: never;
  requestBodies: {
    /** @description articleのリクエスト */
    articleEntity: {
      content: {
        "application/json": components["schemas"]["articleEntity"];
      };
    };
  };
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
