/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v2/sample": {
    /** sample api */
    get: {
      responses: {
        /** get sample */
        200: {
          schema: definitions["sampleEntity"];
        };
      };
    };
  };
}

export interface definitions {
  sampleEntity: {
    /**
     * Format: int32
     * @description sample id
     */
    id?: number;
  };
}

export interface operations {}

export interface external {}
