/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/articles": {
    /** article entityを全て取得 */
    get: {
      responses: {
        /** get article */
        200: {
          schema: definitions["articleEntities"];
        };
        /** articleが存在しない */
        404: unknown;
      };
    };
    /** articleの追加 */
    post: {
      parameters: {
        body: {
          /** articleのリクエスト */
          article: definitions["articleEntity"];
        };
      };
      responses: {
        /** post article */
        200: {
          schema: definitions["articleEntity"];
        };
      };
    };
  };
  "/v2/article/{id}": {
    /** article(単体)の取得 */
    get: {
      parameters: {
        path: {
          /** article id */
          id: number;
        };
      };
      responses: {
        /** get article */
        200: {
          schema: definitions["articleEntity"];
        };
      };
    };
    /** articleの更新 */
    put: {
      parameters: {
        path: {
          /** article id */
          id: number;
        };
        body: {
          /** articleのリクエスト */
          article: definitions["articleEntity"];
        };
      };
      responses: {
        /** put article */
        200: {
          schema: definitions["articleEntity"];
        };
      };
    };
    /** articleの削除 */
    delete: {
      parameters: {
        path: {
          /** article id */
          id: number;
        };
      };
      responses: {
        /** delete article */
        200: {
          schema: definitions["articleEntity"];
        };
      };
    };
  };
}

export interface definitions {
  /** @description 記事 */
  articleEntity: {
    /**
     * Format: int32
     * @description 記事を一意に判定するid
     */
    id?: number;
    /** @description 記事名 */
    name?: string;
    /** @description 記事内容 */
    body?: string;
  };
  /** @description 記事の配列 */
  articleEntities: definitions["articleEntity"][];
}

export interface operations {}

export interface external {}
